---

#- name: we need awscli on 8
#  pip:
#    name: awscli
#    executable: pip3
#  when: (ansible_os_family == "RedHat") and
#        (ansible_distribution_major_version) == "8"

- name: rocky9 needs codereadybuilder
  ansible.builtin.shell:
    cmd: 'dnf config-manager --set-enabled crb'
  when: ansible_distribution == "Rocky" and
        ansible_distribution_major_version == "9"

- name: just use OS-included binary for now
  ansible.builtin.package:
    name: awscli
    state: latest
  when: ansible_os_family == "RedHat"
