---
# dataverse/tasks/dataverse-apache.yml

- name: install Apache for RedHat/CentOS
  yum: 
    name: ['httpd', 'mod_ssl']
    state: latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: install http proxy when SSL disabled
  template:
    src: http.proxy.conf.j2
    dest: /etc/httpd/conf.d/http.proxy.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
        and apache.ssl.enabled == false

- include: dataverse-apache-ssl.yml
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
        and apache.ssl.enabled == true
        and letsencrypt.enabled == false

- include: certbot.yml
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
        and apache.ssl.enabled == true
        and letsencrypt.enabled == true

- name: install proxy error boilerplate
  copy: src=503.html dest=/etc/httpd/conf.d owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: enable and start httpd on RedHat/CentOS 7
  service: name=httpd enabled=yes state=started
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
