---
# dataverse/tasks/dataverse-prereqs.yml

- name: ensure EPEL repository for RedHat7/CentOS7
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

# the 2.3 yum module is throwing tracebacks, lovely.
#- name: update ansible
#  yum: name=ansible state=latest
#  when: ansible_os_family == "RedHat" and
#        ansible_distribution_major_version == "7"
#  tags: prereqs

- name: install java-1.8.0-openjdk-devel for RedHat/CentOS. Dataverse currently requires this version.
  yum: name="{{ item }}" state=latest
  with_items:
    - elinks
    - git
    - java-1.8.0-openjdk-devel
    - jq
    - net-tools
    - perl
    - python-psycopg2
    - unzip
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: prereqs

- name: install ImageMagick for RedHat/CentOS to allow thumbnail generation
  yum: name=ImageMagick state=latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
    - "{{ dataverse.thumbnails }}"
  tags: prereqs
