---

- name: begin make data count task
  debug:
    msg: '##### MAKE DATA COUNT #####'

- name: ensure python3-pip. prereqs already installs python-3.9 on rhel/rocky
  yum:
    name: python39-pip
    state: latest

- name: ensure counter user exists
  user:
    name: "{{ dataverse.counter.user }}"

- name: download zip file
  unarchive:
    src: "https://github.com/CDLUC3/counter-processor/archive/v{{ dataverse.counter.version }}.zip"
    dest: /usr/local
    remote_src: yes
    owner: "{{ dataverse.counter.user }}"

- name: pip install requirements
  shell: "/usr/bin/python3.9 -m pip install -r /usr/local/counter-processor-{{ dataverse.counter.version }}/requirements.txt"
  become: yes

- name: create sample log dir
  file:
    path: "/usr/local/counter-processor-{{ dataverse.counter.version }}/sample_logs"
    owner: "{{ dataverse.counter.user }}"
    state: directory
    mode: 0755

- name: touch sample logs
  shell: 'for i in `echo {00..31}`; do touch /usr/local/counter-processor-{{ dataverse.counter.version }}/sample_logs/counter_2018-05-$i.log; done'
  become: yes
  become_user: "{{ dataverse.counter.user }}"

- name: place config template
  template:
    src: counter-processor-config.yml.j2
    dest: "/usr/local/counter-processor-{{ dataverse.counter.version }}/counter-processor-config.yml"
    owner: "{{ dataverse.counter.user }}"
    mode: 0644

- name: launch counter
  shell:
    cmd: 'cd /usr/local/counter-processor-{{ dataverse.counter.version }} || python3.9 main.py'
  vars:
    CONFIG_FILE: "/usr/local/counter-processor-{{ dataverse.counter.version }}/counter-processor-config.yml"
  become: yes
  become_user: "{{ dataverse.counter.user }}"
