---
# dataverse/tasks/dataverse-prereqs.yml

- name: ensure EPEL repository for RedHat7/CentOS7
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

# fine in vagrant, kills standalone.
#- name: update ansible
#  yum: name=ansible state=latest
#  when: ansible_os_family == "RedHat" and
#        ansible_distribution_major_version == "7"
#  tags: prereqs

- name: let's use the closest centos mirror
  file: path=/var/cache/yum/x86_64/7/timedhosts.txt state=absent
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: makecache
  yum:
    update_cache: yes
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: install java-nnn-openjdk and other packages for RedHat/CentOS.
  yum:
   name: ['bash-completion', 'elinks', 'git', 'java-{{ dataverse.java.version }}-openjdk-devel', 'jq', 'mlocate', 'net-tools', 'perl', 'python-psycopg2', 'sudo', 'unzip', 'vim-enhanced']
   state: latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
  tags: prereqs

- name: install ImageMagick for RedHat/CentOS to allow thumbnail generation
  yum: name=ImageMagick state=latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
    - dataverse.thumbnails
  tags: prereqs
