---

- name: install docker-ce repo
  ansible.builtin.get_url:
    url: '{{ docker.repo }}'
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: install docker-ce
  ansible.builtin.dnf:
    name: ['docker-ce', 'docker-compose-plugin']
    state: latest

- name: Ansible docker module requires python-docker
  ansible.builtin.package:
    name: 'python3-docker'
    state: latest

- name: and docker-compose python package
  ansible.builtin.pip:
    name: docker-compose

- name: ensure /etc/docker exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure cidr range
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  when: docker.cidr is undefined

- name: infer become_user
  ansible.builtin.command: whoami
  register: whoami_output

- name: register docker_user
  ansible.builtin.set_fact:
    docker_user: "{{ whoami_output.stdout }}"

- name: add ansible_ssh_user to docker group
  ansible.builtin.user:
    name: '{{ docker_user }}'
    groups: docker
    append: yes

- name: add dataverse user to docker group
  ansible.builtin.user:
    name: '{{ dataverse.payara.user }}'
    groups: docker
    append: yes

- name: reload systemd, enable docker, start
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
