---

- ansible.builtin.import_tasks: docker.yml

- ansible.builtin.import_tasks: aws_cli.yml

# we only want datastore jvm-options now.
#- ansible.builtin.import_tasks: aws_config.yml

# so we can run localstack task stand-alone
- ansible.builtin.import_tasks: dataverse-fqdn.yml

- name: is hostname_external set
  ansible.builtin.set_fact:
    hostname_external: '{{ public_fqdn }}'
  when: localstack.hostname_external is undefined

- name: place docker-compose.yml template
  ansible.builtin.template:
    src: localstack-compose.yml.j2
    dest: '~{{ dataverse.payara.user }}/localstack-compose.yml'

- name: ensure DATA_DIR exists
  ansible.builtin.file:
    path: '{{ localstack.data_dir }}'
    state: directory
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: 0755

- name: start s3-test container
  ansible.builtin.shell: 'docker compose -f localstack-compose.yml up -d'
  become: true
  become_user: '{{ dataverse.payara.user }}'
  args:
    chdir: '~{{ dataverse.payara.user }}'
