---
# dataverse/tasks/main.yml

- name: begin dataverse ansible role
  debug:
    msg: '##### BEGIN ANSIBLE ROLE #####'

- ansible.builtin.import_tasks: sanity-checks.yml
  tags:
  - prereqs

- ansible.builtin.import_tasks: dataverse-prereqs.yml
  tags: 
  - prereqs

- ansible.builtin.import_tasks: dataverse-required-variables.yml
  tags:
   - always

- ansible.builtin.import_tasks: ansible-scripts.yml
  tags:
   - always
   - scripts

- ansible.builtin.import_tasks: rserve.yml
  when: rserve.install == true
  tags:
  - rserve

- ansible.builtin.import_tasks: dataverse-fqdn.yml
  tags:
   - prereqs
   - apache
   - fqdn
   - dataverse

- ansible.builtin.import_tasks: sshkeys.yml
  when: sshkeys.enabled == True
  tags:
  - sshkeys

- ansible.builtin.import_tasks: postfix.yml
  when: postfix.enabled == true
  tags:
  - postfix

- ansible.builtin.import_tasks: dataverse-apache.yml
  when: apache.enabled == True
  tags:
  - apache

- ansible.builtin.import_tasks: postgres.yml
  when: db.postgres.enabled == True
  tags:
  - postgres

- ansible.builtin.import_tasks: dataverse-branch.yml
  when: dataverse_branch != "release"
  tags:
  - dataverse

- ansible.builtin.import_tasks: jacoco-download.yml
  when: dataverse.jacoco.enabled == true and
        dataverse_repo != "release"

- ansible.builtin.import_tasks: dataverse-installer.yml
  tags:
  - payara

- ansible.builtin.import_tasks: payara.yml
  tags:
  - payara

- ansible.builtin.import_tasks: solr.yml
  tags:
  - solr

- ansible.builtin.import_tasks: localstack.yml
  when: localstack.enabled == true
  tags:
  - localstack

- ansible.builtin.import_tasks: s3.yml
  when: s3.enabled == true
  tags:
  - s3

- ansible.builtin.import_tasks: localstack_create.yml
  when: localstack.enabled == true
  tags:
  - localstack 

- ansible.builtin.import_tasks: dataverse-install.yml
  tags:
  - dataverse

- ansible.builtin.import_tasks: dataverse-storage.yml
  when: dataverse.filesdirs[0] is defined
  tags:
  - storage

- ansible.builtin.import_tasks: dataverse-postinstall.yml
  tags:
  - postinstall

- ansible.builtin.import_tasks: dataverse-frontend.yml
  tags:
  - frontend
  when: dataverse.frontend.enabled

- ansible.builtin.import_tasks: dataverse-gui.yml
  tags:
  - gui
  when: dataverse.branding.enabled

- ansible.builtin.import_tasks: shibboleth.yml
  when: shibboleth.enabled == True
  tags:
  - shibboleth

- ansible.builtin.import_tasks: orcid.yml
  when: orcid.enabled == "true"
  tags:
  - orcid

- ansible.builtin.import_tasks: sampledata.yml
  when: dataverse.sampledata.enabled == true
  tags:
  - sampledata

- ansible.builtin.import_tasks: custom_sampledata.yml
  when: dataverse.custom_sampledata.enabled == true
  tags:
  - custom_sampledata

- ansible.builtin.import_tasks: dataverse-counter.yml
  when: dataverse.counter.enabled == true
  tags:
  - counter

- ansible.builtin.import_tasks: dataverse-previewers.yml
  when: dataverse.previewers.enabled == true
  tags:
  - previewers

- ansible.builtin.import_tasks: dataverse-languages.yml
  when: dataverse.language.enabled == true
  tags:
  - languages

- ansible.builtin.import_tasks: dataverse-licenses.yml
  when: dataverse.licenses.enabled == true
  tags:
  - licenses

- ansible.builtin.import_tasks: dataverse-externaltools.yml
  tags:
  - externaltools

- ansible.builtin.import_tasks: prometheus.yml
  when: prometheus.install == true
  tags:
  - prometheus

- ansible.builtin.import_tasks: dataverse-api-testsuite.yml
  when: dataverse.api.test_suite == true
  tags:
  - apitestsuite

- ansible.builtin.import_tasks: jacoco-generate_report.yml
  when: dataverse.jacoco.enabled == true and
        dataverse_repo != "release"

- ansible.builtin.import_tasks: build_guides.yml
  when: build_guides == true
  tags:
  - build_guides

- ansible.builtin.import_tasks: munin.yml
  when: munin.install == true
  tags:
  - munin

- ansible.builtin.import_tasks: pg_backups.yml
  when: db.backups.enabled == true
  tags:
  - pg_backups

- ansible.builtin.import_tasks: schemaspy.yml
  when: schemaspy.enabled == true
  tags:
  - schemaspy

- ansible.builtin.import_tasks: fin.yml
  
