---
# dataverse/tasks/main.yml

- include: dataverse-prereqs.yml
  tags: prereqs

- include: rserve.yml
  when: rserve.install == true
  tags: rserve

- include: dataverse-fqdn.yml
  tags: prereqs

- include: sshkeys.yml
  when: sshkeys.enabled == True
  tags: sshkeys

- include: dataverse-apache.yml
  tags: apache

- include: dataverse-shibboleth.yml
  when: shibboleth.enabled == True
  tags: shibboleth

- include: postgres.yml
  tags: postgres

- include: dataverse-branch.yml
  when: dataverse_branch != "release"

- include: dataverse-glassfish.yml
  tags: glassfish

- include: dataverse-get-release.yml
  tags: release

- include: dataverse-solr.yml
  tags: solr

- include: dataverse-install.yml
  tags: dataverse

- include: dataverse-postinstall.yml
  tags: postinstall

- include: sampledata.yml
  when: dataverse.sampledata.enabled == true
  tags: sampledata

- include: custom_sampledata.yml
  when: dataverse.custom_sampledata.enabled == true
  tags: custom_sampledata

- include: dataverse-counter.yml
  when: dataverse.counter.enabled == true
  tags: counter

- include: dataverse-previewers.yml
  when: dataverse.previewers.enabled == true
  tags: previewers

- include: dataverse-externaltools.yml
  when: dataverse.externaltools.enabled == true
  tags: externaltools

- include: dataverse-api-testsuite.yml
  when: dataverse.api.test_suite == true
  tags: test_suite

- include: munin.yml
  when: munin.install == true
  tags: munin

- include: prometheus.yml
  when: prometheus.install == true
  tags: prometheus

- name: Fin
  debug: msg="Dataverse installation complete! Please check output logs in /tmp for further review."
