---
# dataverse/tasks/main.yml

- name: begin dataverse ansible role
  debug:
    msg: '##### BEGIN ANSIBLE ROLE #####'

- include: sanity-checks.yml
  tags:
  - prereqs

- include: dataverse-prereqs.yml
  tags: 
  - prereqs

- include: dataverse-required-variables.yml
  tags:
   - payara
   - dataverse
   - storage
   - postinstall
   - s3
   - gui

- include: rserve.yml
  when: rserve.install == true
  tags:
  - rserve

- include: dataverse-fqdn.yml
  tags:
   - prereqs
   - apache

- include: sshkeys.yml
  when: sshkeys.enabled == True
  tags:
  - sshkeys

- include: postfix.yml
  when: postfix.enabled == true
  tags:
  - postfix

- include: dataverse-apache.yml
  tags:
  - apache

- include: postgres.yml
  tags:
  - postgres

- include: dataverse-branch.yml
  when: dataverse_branch != "release"

- include: jacoco-download.yml
  when: dataverse.jacoco.enabled == true and
        dataverse_repo != "release"

- include: dataverse-download.yml
  tags:
  - payara

- include: payara.yml
  tags:
  - payara

- include: dataverse-get-release.yml
  tags:
  - release

- include: solr.yml
  tags:
  - solr

- include: localstack.yml
  when: localstack.enabled == true
  tags:
  - localstack

- include: s3.yml
  when: s3.enabled == true
  tags:
  - s3

- include: localstack_create.yml
  when: localstack.enabled == true
  tags:
  - localstack 

- include: dataverse-install.yml
  tags:
  - dataverse

- include: dataverse-storage.yml
  when: dataverse.filesdirs[0] is defined
  tags:
  - storage

- include: dataverse-postinstall.yml
  tags:
  - postinstall

- include: dataverse-gui.yml
  tags:
  - gui
  when: dataverse.branding.enabled

- include: dataverse-shibboleth.yml
  when: shibboleth.enabled == True
  tags:
  - shibboleth

- include: sampledata.yml
  when: dataverse.sampledata.enabled == true
  tags:
  - sampledata

- include: custom_sampledata.yml
  when: dataverse.custom_sampledata.enabled == true
  tags:
  - custom_sampledata

- include: dataverse-counter.yml
  when: dataverse.counter.enabled == true
  tags:
  - counter

- include: dataverse-previewers.yml
  when: dataverse.previewers.enabled == true
  tags:
  - previewers

- include: dataverse-externaltools.yml
  tags:
  - externaltools

- include: prometheus.yml
  when: prometheus.install == true
  tags:
  - prometheus

- include: schemaspy.yml
- include: dataverse-api-testsuite.yml
  when: dataverse.api.test_suite == true
  tags:
  - apitestsuite

- include: jacoco-generate_report.yml
  when: dataverse.jacoco.enabled == true and
        dataverse_repo != "release"

- include: build_guides.yml
  when: build_guides == true
  tags:
  - build_guides

- include: munin.yml
  when: munin.install == true
  tags:
  - munin

  when: schemaspy.enabled == true
  tags:
  - schemaspy

- name: Fin
  debug:
    msg: '##### END ANSIBLE ROLE #####'
